[project]

name = "cache_dit"
dynamic = ["version", "dependencies", "optional-dependencies"]
requires-python = ">=3.10"
authors = [{name = "DefTruth, vipshop.com, etc."}]
description = "⚡️DBCache: A Training-free UNet-style Cache Acceleration for Diffusion Transformers"
maintainers = [{name="DefTruth, vipshop.com, etc"}] 
readme = "README.md" 

[project.urls]

Repository = "https://github.com/vipshop/DBCache.git"
Homepage = "https://github.com/vipshop/DBCache.git" 

[build-system]

requires = ["setuptools>=64", "setuptools_scm>=8"]
# build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "python-simplified-semver"
local_scheme = "no-local-version"

[tool.black]

line-length = 80
target-version = ["py310"]
